### ISSUE TITLE
Change entry action menu

### ISSUE THREAD

**Issue by amirm3hdi** [SavandBros/gonevis-dash#380]
## Tasks

- [ ] Rename to **Pin (Featured)**
- [ ] Rename to **Unpin**
- [ ] Change icon to `fa-pencil`
- [ ] Change icon to `fa-star-o`
- [ ] Change icon to `fa-ban`

## Screenshot
![image](https://cloud.githubusercontent.com/assets/4629328/23975651/896dfbec-09fb-11e7-9ad0-533c61486153.png)
